theme: theme/hollow

deploy:
  type: git
  token: "${GIT_TOKEN}"
  remote: https://github.com/zbysir/zbysir.github.io
  branch: docs

source:
  type: git
  token: "${GIT_TOKEN}"
  remote: https://github.com/zbysir/zbysir.github.io
  branch: master

file:
  img_compression:
    scope: "only_blog" # all：全部静态资源中的图片，only_blog：出现在文章引用中
    width:
    height:
    q:

oss:
  type: qiniu
  access_key: "${QINIU_AK}"
  secret_key: "${QINIU_SK}"
  bucket: bysirblogout
  prefix: blog
  domain: http://blog-static.bysir.top

# 将会 copy 到根目录
assets:
  - statics

# theme_config 字段的值可以在 js 中使用 bblog.getConfig() 获取
theme_config:
  base: ''
  title: Bysir 的博客
  logo: "bysir"
  stack: Tailwindcss + <a href="https://github.com/zbysir/hollow">Hollow</a> + <a href="https://github.com/zbysir/gojsx">Jsx</a>
  footer_links:
    - url: https://github.com/zbysir
      name: GitHub
      icon: GitHub
  links_page: 'pages/links.md'
  about:
    - title: 关于博客
      desc: 建立这个博客的目的是分享经验、记录思维
      content: |
        很久以前就想自己搭建一个博客，记录下自己的东西，但一直没找到合适的工具来搭建博客，故 [写了一个优先满足自己需求的工具](https://github.com/zbysir/hollow)，希望它能承载我所有灵感。
        
        我想在这里记录我灵感和想法，积少成多，连点成线。
    - title: 关于我
      desc: 认真打工，努力不打工
      content: |
        喜欢有逻辑的事物，如编程、悬疑电影。对编程略知一二，更多的是在 Web 领域学习；Golang 作为主力语言，也会一点 Vue、React。
        
        做过有趣的事情是将 Golang 与 Vue、React 结合，比如 [这个项目](https://github.com/zbysir/gojsx)，和 [这个](https://github.com/zbysir/go-vue-ssr)。
        
        还想让编程与“艺术”结合，如音乐、画画、游戏，我也想搞搞艺术。
        
        这还有一些项目是我做的 😉：
        
        - [音乐舞台](https://github.com/zbysir/bgm-stage)
